### ISSUE TITLE
Allow user to remove home capsule

### ISSUE THREAD

**Issue by licaon-kter** [Corewala/Buran#21]
Trying to fix https://github.com/Corewala/Buran/issues/20 I've put a ` ` _(space)_ instead of a link _(I don't want/have a link anyway)_.

The app crashes continuously now and never starts:
```
FATAL EXCEPTION: main
Process: corewala.gemini.buran, PID: 29258
java.lang.RuntimeException: Unable to start activity ComponentInfo{corewala.gemini.buran/corewala.buran.ui.GemActivity}: java.lang.IllegalArgumentException: Illegal character in path at index 0:  
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 0:  
	at java.net.URI.create(URI.java:848)
	at l2.g.b(Unknown Source:4)
	at o2.r.d(Unknown Source:17)
	at o2.r.c(Unknown Source:5)
	at corewala.buran.ui.GemActivity.onCreate(Unknown Source:20)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
	... 11 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 0:  
	at java.net.URI$Parser.fail(URI.java:2893)
	at java.net.URI$Parser.checkChars(URI.java:3066)
	at java.net.URI$Parser.parseHierarchical(URI.java:3150)
	at java.net.URI$Parser.parse(URI.java:3108)
	at java.net.URI.<init>(URI.java:584)
	at java.net.URI.create(URI.java:846)
	... 19 more
```

**Comment by Corewala** [comment]
Fixed
